// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtFBXmtMkQfwq5ODFZ5XaSbFIcyA0ZCAk',
    appId: '1:349388561626:web:d143efd601fce31f7159e3',
    messagingSenderId: '349388561626',
    projectId: 'grandparent-guardian-7b13e',
    authDomain: 'grandparent-guardian-7b13e.firebaseapp.com',
    storageBucket: 'grandparent-guardian-7b13e.firebasestorage.app',
    measurementId: 'G-73ZL3E9P61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMiCptOm44-Jdg_F5Bo6hWEISs9RGVHM',
    appId: '1:349388561626:android:8ff661546615e8ec7159e3',
    messagingSenderId: '349388561626',
    projectId: 'grandparent-guardian-7b13e',
    storageBucket: 'grandparent-guardian-7b13e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6lkxGCax9MSnEGn7xHXHJJB-lkc-hiw',
    appId: '1:349388561626:ios:2841f5a350675d837159e3',
    messagingSenderId: '349388561626',
    projectId: 'grandparent-guardian-7b13e',
    storageBucket: 'grandparent-guardian-7b13e.firebasestorage.app',
    iosBundleId: 'com.example.frontendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6lkxGCax9MSnEGn7xHXHJJB-lkc-hiw',
    appId: '1:349388561626:ios:2841f5a350675d837159e3',
    messagingSenderId: '349388561626',
    projectId: 'grandparent-guardian-7b13e',
    storageBucket: 'grandparent-guardian-7b13e.firebasestorage.app',
    iosBundleId: 'com.example.frontendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtFBXmtMkQfwq5ODFZ5XaSbFIcyA0ZCAk',
    appId: '1:349388561626:web:4b2ea148ee4ade3e7159e3',
    messagingSenderId: '349388561626',
    projectId: 'grandparent-guardian-7b13e',
    authDomain: 'grandparent-guardian-7b13e.firebaseapp.com',
    storageBucket: 'grandparent-guardian-7b13e.firebasestorage.app',
    measurementId: 'G-QCB077ZESL',
  );

}